import type { Metadata } from 'next';
import 'slick-carousel/slick/slick.css';
import 'slick-carousel/slick/slick-theme.css';
import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';

import '@fontsource/great-vibes/400.css';
import './style.css';
import { CssBaseline } from '@mui/material';
import { GlobalThemeProvider } from '@/globalProviders/themeProvider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <CssBaseline />
        <GlobalThemeProvider>{children}</GlobalThemeProvider>
      </body>
    </html>
  );
}
